### ISSUE TITLE
XML Import Example

### ISSUE THREAD

**Issue by pmbittner** [in2code-de/publications#14]
Hi,

I want to use the XML importer for importing my references to the website. Unfortunately, I cannot find any examples or documentation on how XML files have to look like for that purpose. Could you provide some example XML files? In the documentation, it only says:

_"the XML format is a simple format that mirrors all fields"_

which does not help that much.

Thanks in any case!
Paul

**Comment by einpraegsam** [comment]
Good question. @kfumy Do you have an example XML-File for the imports? If so, we could add it to the documentation.

**Comment by pmbittner** [comment]
Hi einpraegsam,

thanks for your response. Do you know any other projects using this format already where I could take a look?

**Comment by kfumy** [comment]
Hi Paul, we at Uni Ulm use the Publication Extension.
Unfortunately I have no Test xml File ready for you.
I would suggest, that you create an example for every publication type in the TYPO3 backend by hand and export it in bibtex or xml throug the plugin.

Then delete your created publications and import your file.
That should work. Afterwords you have the example file of the needed formatting. 
We in Ulm use the importer rarely, so we have not too much experience with it.

**Comment by pmbittner** [comment]
Ok I will try that! Thanks ☺️

**Comment by pmbittner** [comment]
Wouldn't it still be helpful for future users to have an example?
