### ISSUE TITLE
BUG: Author Name Dropped After Umlaut in BibTeX Import

### ISSUE THREAD

**Issue by pmbittner** [in2code-de/publications#16]
Hi all,

when importing the following BibTeX into Typo3, I get a wrong username for `Thomas Thüm`.

```
@inproceedings{YWT:SPLC20,
  author = {Jeffrey Young and Eric Walkingshaw and Thomas Thüm},
  title = {Variational Satisfiability Solving},
  year = {2020},
  booktitle = {Proc. Int'l Systems and Software Product Line Conf. (SPLC)},
  address = {New York, NY, USA},
  publisher = {ACM}
}
```

![grafik](https://user-images.githubusercontent.com/9421337/90618281-0a658180-e210-11ea-8f68-cc4ccca9baad.png)

**Comment by pmbittner** [comment]
This bug was encoding related. I switched the encoding of my input file to UTF-8 and it worked. A short hint that UTF-8 (possibly amongst others) is required, or an error message upon parser failure would be helpful though.

**Comment by einpraegsam** [comment]
Yes, UTF-8 is the default format for TYPO3 and modern websites in general. If you really think, that this note would help others, feel free to make a documentation pull request with a sitenote.
