### ISSUE TITLE
Unknown type: check, render type: checkboxToggle in publications tca

### ISSUE THREAD

**Issue by epxfrho** [in2code-de/publications#17]
Using publications 1.17.0 with Typo3 8.7.X, I get a TCA error "Unknown type: check, render type: checkboxToggle" inside the publications record. The property "renderType" for checkboxes was introduced in Typo3 9.
![publications-typo387-hiddenfield](https://user-images.githubusercontent.com/53036969/91991469-35cd8d80-ed33-11ea-97be-7c9730501cc8.jpg)

**Comment by mschwemer** [comment]
Even TYPO3 V9 is in ELTS by now, so we can close the issue. Current versions are compatible with V9 and V10. V11 compatibility ahead.
