### ISSUE TITLE
Feedback languages, templates

### ISSUE THREAD

**Issue by ivonnenordhausen** [in2code-de/publications#2]
Hej alex, 

i installed publications now in composer mode and it works very fine. Thank you for investement!
Now i will revise some templates (create probally new citation style) and i adjust/ replace some markers in the fluid templates. How can i communicate this changes to you or rather to the project? 

Thx, Ivonne

**Comment by einpraegsam** [comment]
Hi Ivonne,

we love to read that you like the extension. If you change is valuable for all users, we could integrate new citestyles into it. Maybe @kfumy has to decide which change will make it into the extension itself :)

Alex

**Comment by kfumy** [comment]
Hi Ivonne,
I suggest, that you copy the CiteStyle1.html in the extension, which represents the IEEE Standard. From there you can make your changes. Of course, it would be very preferrable, if you create a widespread official CiteStyle, like APA, Harvard or Chicago...
What I have learned so far, is that there are some differences between official CiteStyle rules and the needs of our professors. In general, they want to have more fields visible in the frontend (like WebURLs, fileURLs, etc.) for the different publicationtypes, as they are defined by the rule. But that is ok with me.
I would be glad, if we get new citestyles in the extension.
Perhaps you sent your new citestyle to Alex, who integrates it in the extension, we test it for our purposes and suggest changes, if we think, there is missing something...
Cheers
Klaus

**Comment by mschwemer** [comment]
Hi Ivonne, hi @all

Thanks for your input. 

There is a documentation about how to add new citestyles. 

https://github.com/in2code-de/publications/blob/develop/Documentation/Citestyles.md

If you implemented a citestyle, which, you think, will help others, please open a new issue and / or pull request for each cite style. This will help to keep the overview. 

I am closing it for now.
