### ISSUE TITLE
How to install RenanBr/bibtex

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#26]
Trying to install the plugin on a fresh typo3 installation. 
Plugin is installed over the extension manager (v 2.3.0) 

When using the bib importer the following error 

`	
Oops, an error occurred!
Class 'RenanBr\BibTexParser\Parser' not found`

Presumably also this package should be installed: https://github.com/renanbr/bibtex-parser

Could you elaborate on this in the manual for the installation?

**Comment by einpraegsam** [comment]
Please look at https://github.com/in2code-de/publications#technical-requirements - this extension needs to be installed in composer mode only. In classic mode third party packages are not loaded.

**Comment by eBornstein** [comment]
I just had the same problem, local is composer and live unfortunately not. 
The dirty way was to copy the renarn directory from the vendor (local installation) to typo3conf/ext (live installation) and create an ext_emconf.php.

the important part
```
    'autoload' => [
        'psr-4' => [
            'RenanBr\\BibTexParser\\' => 'bibtex-parser/src/'
        ]
    ]
```
After installing the renan extension in backend (TYPO3 10.4.21), the import is working.
