### ISSUE TITLE
ISBN not a link

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#29]
Currently, ISBN entries are displayed in the link block.

The presence of this item makes not much sense and only adds to unnecessary space in the already long list. The argument to remove these are 
1) this is not a link
2) it is not useful to any regular website visitor
3) librarians have their own systems
4) it does not belong to any regular referencing styles

https://github.com/in2code-de/publications/blob/6c13cc48d473bcbd949ebb3af2c5c57ff8bc1050/Resources/Private/Partials/List/Citestyle/LinkBlock.html#L15

One could remove the ISBN info from all entries, but it would be much easier to not render it as it is often part of the import.

**Comment by mschwemer** [comment]
Thanks for your input. 

Basically I can follow your arguments. But removing it from the default partial will now break existing installations. So we will not remove it. 

You still can overwrite the partial in your site-package and remove it there.

**Comment by karliwalti** [comment]
Thank you for having looked into it.
