### ISSUE TITLE
Mandatory TEXT fields break import with MySQL Strict mode

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/publications#3]
# Abstract

When the database uses SQL Strict Mode, all fields of type TEXT **must** be provided in any BIB or XML file being imported.

Those fields currently are:
* title
* abstract
* keywords
* tags
* address
* booktitle

# Cause

Several optional Bibtex fields are mapped to `NOT NULL` database fields of type `TEXT`. 
It is not possible to provide a default value for TEXT, which leads to Bibtex import failing with [MySQL strict mode](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-strict).

# Fix

A simple fix for it would be to remove `NOT NULL` from the [`ext_tables.sql`](https://github.com/in2code-de/publications/blob/develop/ext_tables.sql) for all TEXT attributes (eventually excepted `title`, since it is a requirement of the BibTex format).

Before opening a merge request to address it, I just wanted to check with you the reasons of this `NOT NULL` attribute and if it is required for reasons I am not aware of.

**Comment by einpraegsam** [comment]
Thx for your time digging into that issue. I merged your PR. 
Will be published with the next release of EXT:publications.

**Comment by einpraegsam** [comment]
Just released in 1.12.0
