### ISSUE TITLE
frontend rendering can't handle curly brackets 

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#32]
v.2.3.0 

Importing bib files with title in double curly brackets (this is part of standard to force capitalization and other formatting, see also
https://github.com/distillpub/template/issues/93
 https://tex.stackexchange.com/questions/294870/different-behavior-of-double-curly-braces-from-single-curly-braces-and-quotation

ignores the second curly braces and make it part of the title, so

```
@article{Scebba2020,
author = {Scebba, Gaetano and {Da Poian}, Giulia and Karlen, Walter},
doi = {10.1109/TBME.2020.2993649},
eprint = {2004.09834},
issn = {0018-9294},
journal = {IEEE Transactions on Biomedical Engineering},
number = {1},
pages = {350--9},
pmid = {32396069},
title = {{Multispectral Video Fusion for Non-Contact Monitoring of Respiratory Rate and Apnea}},
url = {https://ieeexplore.ieee.org/document/9091089/},
volume = {68},
year = {2021}
}
```

will put in the title field to: {{Multispectral Video Fusion for Non-Contact Monitoring of Respiratory Rate and Apnea}},

This is per se not wrong, as when it is been exported the double bracket should be added again. 
Same for Author, there it is used to force grouping of double name.

A solution could be to remove additional curly brackets at the time of rendering for frontend display and keep the curly in the database (as is).  This way an import,  export, and import would lead to identical results.

**Comment by kfumy** [comment]
solved with #65
