### ISSUE TITLE
frontend rendering can't handle Latex special escape characters

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#33]
v 2.3.0

Umlaut and other special characters are encoded with latex escape characters surrounded by curly brackets, i.e. in titles and authors section such as

`author = {Leach, Sven and Chung, Ku-young and T{\"{u}}shaus, Laura and Huber, Reto and Karlen, Walter},
`
These are currently not parsed during frontend display.

before simply removing curly brackets as suggested in #32 , conversion of LaTex encoding would be needed first.
It would be possible to also perform this conversion during import, but then the import-export would be not reversible.

**Comment by karliwalti** [comment]
I see that 
https://github.com/in2code-de/publications/blob/develop/Classes/Utility/BibTexUtility.php

takes special characters into account during import, however it does not take into account the curly brackets, see also #32 .
the decoding during import will likely break the export, as the special characters will not be readable by many latex interpreters.

**Comment by kfumy** [comment]
solved with #65
