### ISSUE TITLE
[MILESTONE]TYPO3 V11 Compatibility

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/publications#39]
For future installations, we need a compatibility for TYPO3 V11.

This a milestone ticket.

**Comment by mschwemer** [comment]
@kfumy @karliwalti 

I ask you for some support while working on the V11 compatibility upgrade. 

I miss testing data for the importer  and the bib migration. Can you provide example data, that I can use? 

We should add this to the repository also for further reference.

TIA

**Comment by karliwalti** [comment]
Need anything specific? 
I could provide a bib file that covers many cases.

**Comment by karliwalti** [comment]
Need anything specific? 
I could provide a bib file that covers many cases.

**Comment by mschwemer** [comment]
No, nothing specific. 

Such a file would be really helpful. Sounds good.

**Comment by karliwalti** [comment]
Please find attached a challenging test set with various types and special characters. 

[testCollection.zip](https://github.com/in2code-de/publications/files/8154822/testCollection.zip)

In addition, I recommend to use the sample bib files provided by the IEEEtran bibtex package:
https://ctan.org/tex-archive/macros/latex/contrib/IEEEtran/bibtex
these should be comprehensive, but as so often with bibtex, only applies to said style (your Citestyle1 I believe) 

Hope this helps.

**Comment by mschwemer** [comment]
Current development branch is TYPO3 V11 compatible. 

Release will follow soon.
