### ISSUE TITLE
[BUG] vancouver style for inbook

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#44]
inbook is calling book style at https://github.com/in2code-de/publications/blob/f31e50cf6e6e043f7161af91486d989eaf79c62e/Resources/Private/Partials/List/Citestyle/Citestyle9.html#L48

 in this case ,the author rendering for editor in book should not be called
https://github.com/in2code-de/publications/blob/df904706e865694d01ba52bb65e5bfeb7b88bf9a/Resources/Private/Partials/List/Citestyle/Citestyle9.html#L28

I will check how this can be done without duplicating the book style.

**Comment by mschwemer** [comment]
Why not replace 

https://github.com/in2code-de/publications/blob/df904706e865694d01ba52bb65e5bfeb7b88bf9a/Resources/Private/Partials/List/Citestyle/Citestyle9.html#L48

with the needed details and remove the author stuff there? So no additional citestyle would be needed. 

P.S.: I'm trying to get the V11 release out and would like to have as many PR and issues closed before. :-)

**Comment by mschwemer** [comment]
As the releated PR is merged, I will close this issue
