### ISSUE TITLE
Links generated for Groups are only valid for current subpage

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#48]
# current situation #
the plugin offers to display on top a box with links to group sections if grouping (i.e. year or type) is activated.

When there are lot´s of publications, these are spread over several subpages. 

The grouplinks are however only referring to the anchors in the current active page 

the code is generated here https://github.com/in2code-de/publications/blob/c6cbeea108b0b5678b485112233b64814bc11fff/Resources/Private/Partials/List/GroupLinks.html#L15.

# desired situation #
The groulinks not only point to the correct anchor, but also subpage where this anchor is placed.

# solution #
This is essentially the addition of `?tx_publications_pi1[%40widget_0][currentPage]=`
The question is how to find out on which page the anchor is.

**Comment by kfumy** [comment]
in2code will find a solution for this bug.

**Comment by sebastianstein** [comment]
This issue was resolved with commit #[e0a6e06](https://github.com/in2code-de/publications/commit/e0a6e0674b643b6ac781510d8958f3ee310d6ed4)

**Comment by karliwalti** [comment]
See my comment in https://github.com/in2code-de/publications/blob/e0a6e0674b643b6ac781510d8958f3ee310d6ed4/Classes/Domain/Service/PublicationService.php#L35 
Still small bug with missing `$itemPerPage`

**Comment by sebastianstein** [comment]
Hello @karliwalti,

thank you very much for the hint to the still existing bug. I have fixed it with commit #f983633 

Greetings
