### ISSUE TITLE
Highlighting authors seems to no longer work  with Typo3 11.

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#53]
### issue 
the author filter permitted to highlight the search authors, this seems to no longer work.

### desired behavior 
bold author names who was filtered for

### reproduce
1. select an author in the backend filter tab
2. enable the checkbox for highlighting authors in same tab
3. select citestyle9 (Vancouver for web), others might have same issue...
4. inspect frontend

### relevant code
https://github.com/in2code-de/publications/blob/ceaede26bf3e96ab407c0a75b1b71342bbfcf9b5/Resources/Private/Partials/List/Citestyle/Citestyle9.html#L222

**Comment by kfumy** [comment]
might be, that the connected viewhelper function does not work anymore?
