### ISSUE TITLE
French Umlaut with curly brackets are still missing

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#55]
At https://github.com/in2code-de/publications/blob/develop/Classes/Utility/BibTexUtility.php#L187 the German Umlaute were added, but the most common French ones are still missing. these are:

 {\'{e}} and {\`{e}} and {\^{e}} and {\^{o}}  and {\c{s}}

the results should be the same as without curly brackets.

**Comment by kfumy** [comment]
Hi Mr. Karlen, 
I added a feature branch frenchUmlauts and put in the missing french Umlaute. But as I did not understand well the right writing convention, please have a look at it:
https://github.com/in2code-de/publications/blob/frenchUmlaute/Classes/Utility/BibTexUtility.php#L187

**Comment by karliwalti** [comment]
I just opened a pull request for a full commit of missing signs  #61

**Comment by kfumy** [comment]
please, can you send me a test set for the relevant bibtex possibilities? Then I can test it and make a pull request ...

**Comment by karliwalti** [comment]
Just added a pull request #62 that also fixes #57 in the same file. 


Attached the test file (please rename it to .bib
[TestLibraryPublications.txt](https://github.com/in2code-de/publications/files/9869881/TestLibraryPublications.txt)

**Comment by kfumy** [comment]
I testet your file, the special chars are not all converted, see screenshot
<img width="1215" alt="Bildschirmfoto 2022-11-03 um 13 50 33" src="https://user-images.githubusercontent.com/28557574/199725452-4421b3e7-2a73-4820-b1e0-8d0ccbe7f13a.png">

**Comment by karliwalti** [comment]
Da passiert noch einiges schief im Moment, welches noch nicht alles nachvollziebar ist. Wahrscheinlich hat dies wieder mit der Reihenfolge in der Tabelle zu tun, analog fix #[6d70ece](https://github.com/in2code-de/publications/commit/6d70ece95bdf8a2cf7c382a3d1bc98e8e2620270)

**Comment by karliwalti** [comment]
The issue is that not all programs export bibtex files equally. There are at least 3 ways of outputting special characters. In addition, still some chars were not in the table. 
I have now reorganized the array, and added a decoding array that will capture more cases. You can find it in  #64 . Please let me know if ti work in your test env too.

**Comment by kfumy** [comment]
hm, die Änderungen machen alles eher noch kaputter...
<img width="1074" alt="Bildschirmfoto 2022-11-07 um 16 47 01" src="https://user-images.githubusercontent.com/28557574/200354304-b0e748c3-6e65-4e81-b47d-7935c42128d1.png">

**Comment by kfumy** [comment]
so im Frontend:
<img width="1346" alt="Bildschirmfoto 2022-11-07 um 16 47 59" src="https://user-images.githubusercontent.com/28557574/200354410-410be4e1-f20a-4ed2-8650-e3e6d1198303.png">

**Comment by karliwalti** [comment]
Es macht gar nichts...

**Comment by karliwalti** [comment]
Welche php version wird da genutzt?
Undf gibt es eine fehlermeldung dazu im typo3 log?

**Comment by kfumy** [comment]
php 7.4.30
es sind keine Fehler diesbezüglich vorhanden, denn er importiert ja erfolgreich, nur wird nichts decodiert..., die Zeichen werden halt so umgesetzt wie importiert.

**Comment by karliwalti** [comment]
Bitte https://github.com/in2code-de/publications/blob/475d1941335510c374daf38745647f6df0863d10/Classes/Utility/BibTexUtility.php#L80
wiefolgt wechseln: 
`return str_replace(self::$decoding, self::$decoded, $string);`

**Comment by kfumy** [comment]
so sieht es viel besser aus :-)
<img width="676" alt="Bildschirmfoto 2022-11-08 um 08 30 49" src="https://user-images.githubusercontent.com/28557574/200501927-525b8f00-4e31-4c47-b55c-79a69e69c16c.png">

**Comment by kfumy** [comment]
im FE noch nicht ganz perfekt:
<img width="1314" alt="Bildschirmfoto 2022-11-08 um 08 32 46" src="https://user-images.githubusercontent.com/28557574/200502024-fbf3abc3-70f9-465a-868f-6fea1c962ae6.png">

**Comment by kfumy** [comment]
Für È und Ê hab ich selbst hinbekommen. Das č weiss ich nicht, wie ich das anstellen soll...

**Comment by karliwalti** [comment]
Das ş  \c{s} war leider noch nicht drinn:
 
muss das zeichen noch in zeile https://github.com/in2code-de/publications/blob/475d1941335510c374daf38745647f6df0863d10/Classes/Utility/BibTexUtility.php#L22 ergänzt werden. 
Danach die Zeile mit den "s" vor die zeile mit "c" schieben (natürlich in allen drei  arrays).

**Comment by kfumy** [comment]
habs hinbekommen, funzt. :-)
Jetzt fehlt noch, dass die Funktion, die für die Abkürzung der Vornamen zuständig ist, diese auch rendert, wenn der Vornamen mit einem Sonderzeichen beginnt...
<img width="740" alt="Bildschirmfoto 2022-11-08 um 11 22 59" src="https://user-images.githubusercontent.com/28557574/200539853-386094dc-5bd9-4fbb-bcd1-530fc1aa8784.png">

**Comment by kfumy** [comment]
<img width="1334" alt="Bildschirmfoto 2022-11-08 um 11 22 39" src="https://user-images.githubusercontent.com/28557574/200539911-a14cd1d5-5a9d-4c06-8507-126c76af0638.png">

**Comment by kfumy** [comment]
<img width="1314" alt="Bildschirmfoto 2022-11-08 um 11 24 30" src="https://user-images.githubusercontent.com/28557574/200540342-62f8ac26-f699-43dd-a10f-d87fd78a857c.png">

**Comment by karliwalti** [comment]
The full list of latex characters can be found here: https://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf 
This list is huge, and in case some of them will be used in the abstract, it might be imported wrongly. therefore, I suggest to use a latex engine for the abstract in the future.

**Comment by kfumy** [comment]
ups, seems so.
But for the moment the solution fits much better, than before...

**Comment by karliwalti** [comment]
There are still 3 issues to clarify:
1. Special Char acronym for names: Check whether special char here: https://github.com/in2code-de/publications/blob/395846c586b5816a9e6ff4a7a5629443d1e96a56/Classes/ViewHelpers/Format/InitialsViewHelper.php#L32
2. A comma and empty space in year brackets for Mörgeli et al: This seems to be a rendering of the month which can deal only with numbers.  solution: fix template with either https://github.com/in2code-de/publications/blob/395846c586b5816a9e6ff4a7a5629443d1e96a56/Resources/Private/Partials/List/Citestyle/Citestyle4.html#L20 replace "{publication.month}" with <publications:format.monthNameFromNumber month="{publication.month}" limit="3"/> or  return characters instead of empty in https://github.com/in2code-de/publications/blob/395846c586b5816a9e6ff4a7a5629443d1e96a56/Classes/ViewHelpers/Format/MonthNameFromNumberViewHelper.php#L43 or remove month from template altogether (best)
3.  There is unfortunately a space after  A in Alesund. Likely this is due to a mistake in the template and not the  conversion itself: keep as is.

**Comment by kfumy** [comment]
to 3) the space after A in Alesund is in the imported bibfile...

**Comment by kfumy** [comment]
to 2) As far as I remember, the month was included, because of sorting reasons. I will keep it in the template, but try your suggestion.

**Comment by kfumy** [comment]
I have a solution for the issue 2, with the month, I expanded in my local environment the monthNameFromNumber class to catch and format month names, if the importer imports month names as strings, not as numbers.
and for issue 3 also, I put the Templates more inline, then the space dissapears...
Could you provide a solution for issue 1?

**Comment by karliwalti** [comment]
Could you try this?

it would also solve #63

```
    /**
     * @return string
     */
    public function render(): string
    {
        /** Reformat already stored Initials */
        $names_temp=str_replace('.',' ',$this->renderChildren());
        /** Pick initial from each name and stich together with spacer*/
        $names = GeneralUtility::trimExplode(' ', $names_temp, true);
        $initials='';
        foreach ($names as $name) {
            $initials .= $name[0] . $this->arguments['suffix'] . $this->arguments['glue'];
        }
        return rtrim($initials, $this->arguments['glue']);
    }
```

**Comment by kfumy** [comment]
it solves #63, but not issue 1 of this thread..., see screenshot
<img width="1321" alt="Bildschirmfoto 2022-11-24 um 15 02 59" src="https://user-images.githubusercontent.com/28557574/203803467-39b5fbee-e3c9-4c58-b966-64e30b859a78.png">

**Comment by karliwalti** [comment]
I don´t see the issue at the moment. The function trimExplode seems allright.

Could you try the following 2 outputs?
1) Add a second name in the benchmark i.e. Mörgeli, Änis Elvira

2) replace $name[0] with $name in code (only for debugging purpose)

**Comment by kfumy** [comment]
only setting a second Name does not work.
Changing name[0] to name seems to work for special Chars, see screenshot.

<img width="1149" alt="Bildschirmfoto 2022-11-25 um 09 11 52" src="https://user-images.githubusercontent.com/28557574/203933213-73bd63f6-79e1-4e1c-848f-5133e32c62a7.png">

**Comment by karliwalti** [comment]
Does setting a second name display ".E.," or nothing like before?

**Comment by kfumy** [comment]
it displays nothing.
I changed the name[0] now with a substr Funktion and set the length of the substring to 3. That gave this interesting picture...

<img width="1113" alt="Bildschirmfoto 2022-11-25 um 09 35 18" src="https://user-images.githubusercontent.com/28557574/203937242-2b84ff8a-c320-4407-8b23-6da7138d3a50.png">

**Comment by kfumy** [comment]
it seems that special Chars count as 2???
here is my code:
 foreach ($names as $name) {
            $firstletter = substr($name, 0, 3);
            $initials .= $firstletter . $this->arguments['suffix'] . $this->arguments['glue'];
        }

**Comment by karliwalti** [comment]
Yes it is a multibyte encoding. Unfortunately it does not need to be limited to 2 bytes. 
Therefore, third thing to try:
3) replace '$name[0]' with 'mb_substr($name, 0, 1)'

**Comment by kfumy** [comment]
cheerio, it works. :-)

**Comment by kfumy** [comment]
so I make a pull request... :-)

**Comment by kfumy** [comment]
solved with #65
