### ISSUE TITLE
CSS stylesheet file missing?

### ISSUE THREAD

**Issue by knbknb** [in2code-de/publications#58]
I have just upgraded to `publications v3.0.0`. because I still run TYPO3 v10. Moreover I am a newcomer to this extension. I have just installed my first publicationslist as Content Element that actually works, so I am not so familiar with the implementation details of `publications`.

I've noticed that for example in file `typo3conf/ext/publications/Resources/Private/Partials/Plugin/publications/List/Citestyle/LinkBlock.html`  there is a HTML Attribute `class="publications publications__linkblock"`- however the repo does not contain stylesheets where these styles are defined.

Is this by design? Did a CSS file once exist, and was removed for some reason?

**Comment by einpraegsam** [comment]
There is and was never a ready build CSS for this extension and has to be done but the adminstrator.
