### ISSUE TITLE
InitialsViewhelper trims too many names

### ISSUE THREAD

**Issue by karliwalti** [in2code-de/publications#63]
## Issue: 
names with 2 or more middle names, which are not fully stored in database, are trimmed to only 2 initials

## Desired output:
InitialsViewHelper  combines all available initials as configured

## detailed description
InitialsViewHelper.php
https://github.com/in2code-de/publications/blob/develop/Classes/ViewHelpers/Format/InitialsViewHelper.php
 is used to format names in citestyles. Often, longer names (more than 1 middle name) are already compressed in the database like : "Rambo, John J.P."
Another example is given in the uploaded test bib collection 
https://github.com/in2code-de/publications/files/9869881/TestLibraryPublications.txt

the viewhelper does not recognize that the middle names are multiple, as they are separated by a '.'

## suggested solution
explode name for ' ' and '.' in viewhelper https://github.com/in2code-de/publications/blob/395846c586b5816a9e6ff4a7a5629443d1e96a56/Classes/ViewHelpers/Format/InitialsViewHelper.php#L30

**Comment by kfumy** [comment]
solved with #65
