### ISSUE TITLE
[FATAL] Extension breaks system

### ISSUE THREAD

**Issue by BastianBalthasarBux** [in2code-de/publications#69]
The version in TER breaks the system completely.

If an extension does not work in none-composer mode, maybe it's not the very best idea to add it TER. Just my two cents.

**Comment by einpraegsam** [comment]
I'm not sure if we have forgotten to describe it, but yes - as far as I remember, we set on composer mode. Nevertheless we always offer our extensions also in TER because this is more a place where all TYPO3 extensions are listed. Mabe the TER needs a `composer only` flag.

**Comment by BastianBalthasarBux** [comment]
It's somewhere in the "external Docs" (aka github readme).
It's just that I am not aware anymore, that I could break a system with an extension which is installable from TER without any warnings first.
Which is in general a very good sign for the overall quality of the extensions in TER, compared to the "good old times".
Yes, maybe TER needs some "composer only" flag, which then warns if one wants to install via EM.
Anyways, making that extension non-composer working was pretty much a no brainer, at least for the backend, did not try frontend by now.

**Comment by BastianBalthasarBux** [comment]
[sorry for having been so "drama-queen" with that "fatal" ... ;)]
